export const EXERCISES_LIST_REQUEST = 'EXERCISES_LIST_REQUEST ';
export const EXERCISES_LIST_RECEIVED = 'EXERCISES_LIST_RECEIVED';
export const EXERCISES_LIST_ERROR = 'EXERCISES_LIST_ERROR';
export const EXERCISES_LIST_ADD = 'EXERCISES_LIST_ADD';


export const THERAPISTS_LIST_REQUEST = 'THERAPISTS_LIST_REQUEST ';
export const THERAPISTS_LIST_RECEIVED = 'THERAPISTS_LIST_RECEIVED';
export const THERAPISTS_LIST_ERROR = 'THERAPISTS_LIST_ERROR';
export const THERAPISTS_LIST_ADD = 'THERAPISTS_LIST_ADD';

export const THERAPIST_REQUEST = 'THERAPIST_REQUEST ';
export const THERAPIST_RECEIVED = 'THERAPIST_RECEIVED';
export const THERAPIST_ERROR = 'THERAPIST_ERROR';
export const THERAPIST_ADD = 'THERAPIST_ADD';
export const THERAPIST_UNLOAD = 'THERAPIST_UNLOAD';

export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST ';
export const PATIENTS_LIST_RECEIVED = 'PATIENTS_LIST_RECEIVED';
export const PATIENTS_LIST_ERROR = 'PATIENTS_LIST_ERROR';
export const PATIENTS_LIST_ADD = 'PATIENTS_LIST_ADD';

export const PATIENT_REQUEST = 'PATIENT_REQUEST ';
export const PATIENT_RECEIVED = 'PATIENT_RECEIVED';
export const PATIENT_ERROR = 'PATIENT_ERROR';
export const PATIENT_ADD = 'PATIENT_ADD';
export const PATIENT_UNLOAD = 'PATIENT_UNLOAD';