export const EXERCISES_LIST_REQUEST = 'EXERCISES_LIST_REQUEST ';
export const EXERCISES_LIST_RECEIVED = 'EXERCISES_LIST_RECEIVED';
export const EXERCISES_LIST_ERROR = 'EXERCISES_LIST_ERROR';
export const EXERCISES_LIST_ADD = 'EXERCISES_LIST_ADD';

export const THERAPISTS_LIST_REQUEST = 'THERAPISTS_LIST_REQUEST ';
export const THERAPISTS_LIST_RECEIVED = 'THERAPISTS_LIST_RECEIVED';
export const THERAPISTS_LIST_ERROR = 'THERAPISTS_LIST_ERROR';
export const THERAPISTS_LIST_ADD = 'THERAPISTS_LIST_ADD';

export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST ';
export const PATIENTS_LIST_RECEIVED = 'PATIENTS_LIST_RECEIVED';
export const PATIENTS_LIST_ERROR = 'PATIENTS_LIST_ERROR';
export const PATIENTS_LIST_ADD = 'PATIENTS_LIST_ADD';
