export const EXERCISES_LIST_REQUEST = 'EXERCISES_LIST_REQUEST ';
export const EXERCISES_LIST_RECEIVED = 'EXERCISES_LIST_RECEIVED';
export const EXERCISES_LIST_ERROR = 'EXERCISES_LIST_ERROR';
export const EXERCISES_LIST_ADD = 'EXERCISES_LIST_ADD';

export const EXERCISE_ADDED ='EXERCISE_ADDED';

export const FILE_UPLOADED = 'FILE_UPLOADED';
export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
export const FILE_DELETED = 'FILE_DELETED';
export const FILE_DELETE_REQUEST = 'FILE_DELETE_REQUEST';



export const THERAPISTS_LIST_REQUEST = 'THERAPISTS_LIST_REQUEST ';
export const THERAPISTS_LIST_RECEIVED = 'THERAPISTS_LIST_RECEIVED';
export const THERAPISTS_LIST_ERROR = 'THERAPISTS_LIST_ERROR';
export const THERAPISTS_LIST_ADD = 'THERAPISTS_LIST_ADD';

export const THERAPIST_ADDED ='THERAPIST_ADDED';

export const THERAPIST_REQUEST = 'THERAPIST_REQUEST ';
export const THERAPIST_RECEIVED = 'THERAPIST_RECEIVED';
export const THERAPIST_ERROR = 'THERAPIST_ERROR';
export const THERAPIST_ADD = 'THERAPIST_ADD';
export const THERAPIST_UNLOAD = 'THERAPIST_UNLOAD';

export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST ';
export const PATIENTS_LIST_RECEIVED = 'PATIENTS_LIST_RECEIVED';
export const PATIENTS_LIST_ERROR = 'PATIENTS_LIST_ERROR';
export const PATIENTS_LIST_ADD = 'PATIENTS_LIST_ADD';

export const PATIENT_REQUEST = 'PATIENT_REQUEST ';
export const PATIENT_RECEIVED = 'PATIENT_RECEIVED';
export const PATIENT_ERROR = 'PATIENT_ERROR';
export const PATIENT_ADD = 'PATIENT_ADD';
export const PATIENT_UNLOAD = 'PATIENT_UNLOAD';
export const PATIENT_ADDED ='PATIENT_ADDED';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_ADDED ='USER_ADDED';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_ERROR = 'USER_ERROR';
export const USER_ADD = 'USER_ADD';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';